; generated by Component: ARM Compiler 5.06 update 7 (build 960) Tool: armcc [4d365d]
; commandline armcc [--c99 --asm --gnu -oC:/Users/12603/AppData/Local/Temp/p7opt/main.asm --cpu=Cortex-M3 -O1 -I. -I./SYSTEM/sys -I./SYSTEM/usart -I./SYSTEM/delay -I./Src/JY61P -I./Src/LED -I./Src/Buzzer -I./Src/Motor -I./Src/Posture -I./Libraries/APM32F10x_StdPeriphDriver/inc -I./Libraries/CMSIS/Core/Include -I./Libraries/Device/Geehy/APM32F10x/Include -DAPM32F103xB main.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||.text||, CODE, READONLY, ALIGN=2

main PROC
        BL       SystemClockConfig
        BL       delay_init
        BL       LED_Init
        BL       Buzzer_Init
        BL       Vibrator_Init
        BL       JY61P_Init
        BL       Posture_Init
        MOVS     r4,#0
        MOVS     r5,#0
        MOVS     r6,#0
        MOVS     r7,#0
        MOV      r8,r4
        LDR      r9,|L1.296|
|L1.42|
        BL       JY61P_GetPitch
        STR      r0,[r9,#0]  ; pitch
        MOVS     r1,#0xa
        BL       Posture_Update
        BL       Posture_GetState
        ADDS     r4,r4,#0xa
        ADDS     r5,r5,#0xa
        CBZ      r0,|L1.80|
        CMP      r0,#1
        BEQ      |L1.104|
        CMP      r0,#2
        BEQ      |L1.148|
        CMP      r0,#3
        BNE      |L1.288|
        B        |L1.236|
|L1.80|
        BL       LED_AllOff
        BL       Buzzer_Off
        BL       Vibrator_Off
        MOVS     r4,#0
        MOVS     r5,#0
        MOVS     r6,#0
        MOVS     r7,#0
        MOV      r8,r4
        B        |L1.288|
|L1.104|
        MOVS     r1,#0
        MOV      r0,r1
        BL       LED_Set
        MOVS     r1,#0
        MOVS     r0,#1
        BL       LED_Set
        MOVS     r1,#1
        MOVS     r0,#2
        BL       LED_Set
        BL       Buzzer_Off
        BL       Vibrator_Off
        MOVS     r4,#0
        MOVS     r5,#0
        MOVS     r6,#0
        MOVS     r7,#0
        MOV      r8,r4
        B        |L1.288|
|L1.148|
        MOVS     r1,#0
        MOVS     r0,#2
        BL       LED_Set
        MOVS     r1,#0
        MOV      r0,r1
        BL       LED_Set
        BL       Vibrator_On
        CMP      r4,#0x1f4
        BCC      |L1.198|
        MOVS     r4,#0
        CBZ      r6,|L1.186|
        MOVS     r6,#0
|L1.180|
        CBZ      r6,|L1.190|
        MOVS     r1,#1
        B        |L1.192|
|L1.186|
        MOVS     r6,#1
        B        |L1.180|
|L1.190|
        MOVS     r1,#0
|L1.192|
        MOVS     r0,#1
        BL       LED_Set
|L1.198|
        CMP      r5,#0xc8
        BCC      |L1.288|
        MOVS     r5,#0
        CMP      r8,#0
        BEQ      |L1.224|
        MOV      r8,r5
|L1.212|
        CMP      r8,#0
        BEQ      |L1.230|
        BL       Buzzer_On
        B        |L1.288|
|L1.224|
        MOV      r8,#1
        B        |L1.212|
|L1.230|
        BL       Buzzer_Off
        B        |L1.288|
|L1.236|
        MOVS     r1,#0
        MOVS     r0,#2
        BL       LED_Set
        MOVS     r1,#0
        MOVS     r0,#1
        BL       LED_Set
        BL       Buzzer_On
        BL       Vibrator_On
        CMP      r4,#0xfa
        BCC      |L1.288|
        MOVS     r4,#0
        CBZ      r7,|L1.276|
        MOVS     r7,#0
|L1.270|
        CBZ      r7,|L1.280|
        MOVS     r1,#1
        B        |L1.282|
|L1.276|
        MOVS     r7,#1
        B        |L1.270|
|L1.280|
        MOVS     r1,#0
|L1.282|
        MOVS     r0,#0
        BL       LED_Set
|L1.288|
        MOVS     r0,#0xa
        BL       delay_ms
        B        |L1.42|
        ENDP

|L1.296|
        DCD      ||.data||

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

        AREA ||.data||, DATA, ALIGN=2

pitch
        DCFS     0x00000000 ; 0

;*** Start embedded assembler ***

#line 1 "main.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_pitch____REV16|
#line 208 "./Libraries/CMSIS/Core/Include/cmsis_armcc.h"
|__asm___6_main_c_pitch____REV16| PROC
#line 209

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_pitch____REVSH|
#line 223
|__asm___6_main_c_pitch____REVSH| PROC
#line 224

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_pitch____RRX|
#line 410
|__asm___6_main_c_pitch____RRX| PROC
#line 411

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT main [CODE]
        EXPORT pitch [DATA,SIZE=4]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT SystemClockConfig [CODE]
        IMPORT delay_init [CODE]
        IMPORT LED_Init [CODE]
        IMPORT Buzzer_Init [CODE]
        IMPORT Vibrator_Init [CODE]
        IMPORT JY61P_Init [CODE]
        IMPORT Posture_Init [CODE]
        IMPORT JY61P_GetPitch [CODE]
        IMPORT Posture_Update [CODE]
        IMPORT Posture_GetState [CODE]
        IMPORT LED_AllOff [CODE]
        IMPORT Buzzer_Off [CODE]
        IMPORT Vibrator_Off [CODE]
        IMPORT LED_Set [CODE]
        IMPORT Vibrator_On [CODE]
        IMPORT Buzzer_On [CODE]
        IMPORT delay_ms [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,5
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
